_wandb:
    value:
        cli_version: 0.24.0
        e:
            5uh8dqhh6kvvk7xf1lxpid2nqabuew9k:
                args:
                    - -s
                    - -vv
                    - .
                    - --reference_artifact
                    - exercise_14/preprocessed_data.csv:latest
                    - --sample_artifact
                    - preprocessed_data.csv:latest
                    - --ks_alpha
                    - "0.05"
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "2160158191616"
                        used: "312723988480"
                email: sskhattab@gmail.com
                executable: /home/student/.conda/envs/mlflow-cd65784bf8e7fffc45c3ae66d3b5f5d3b28be86d/bin/python3.13
                git:
                    commit: 96b4c8f421fac8779636cb60ecd64d637057514b
                    remote: https://github.com/sam-khatab/genre_classification
                host: 3d552555e05aaeeb613fb400a93a58b58bf142d0-69b57b7cf9-bzxp9
                memory:
                    total: "135077654528"
                os: Linux-6.6.97+-x86_64-with-glibc2.36
                program: /home/student/.conda/envs/mlflow-cd65784bf8e7fffc45c3ae66d3b5f5d3b28be86d/bin/pytest
                python: CPython 3.13.13
                root: /workspace/genre_classification/check_data
                startedAt: "2026-04-23T12:54:36.653762Z"
                writerId: 5uh8dqhh6kvvk7xf1lxpid2nqabuew9k
        m: []
        python_version: 3.13.13
        t:
            "4": 3.13.13
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
